###
POST http://localhost:2000/auth/login
Content-Type: application/json

{
   "userLog" : "test123",
   "password": "password12345"
}

###
GET http://localhost:2000/auth/token


###
GET  http://localhost:2000/auth/userList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlc3Rlc3QiLCJ1c2VybmFtZSI6InRlc3QxMjMiLCJpc0FkbWluIjpmYWxzZSwiY3JlYXRlZEF0IjoiMjAyMy0wMi0wMlQxNTowODoyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMy0wMi0wNlQxNDo1OTozMi4wMDBaIiwiaWF0IjoxNjc1NzM4NzA2LCJleHAiOjE2NzU3Mzg3MjF9.ziVtem6JE88Bgi0ZJw4KG30iR5ftyna5lvpF65hIZps

###
